const menu = [
  {
    id: 1,
    title: "Chicken haleem",
    category: "dinner",
    price: "60₹",
    restaurant: "restaurant: lucky kabab",
    img: "./images/Chicken haleem lucky kabab.jpg",
    desc: ` Address:4-165 SY-139/B, Gandi Maisamma, hyderabad - 500043, Near Gandi Maisamma X Road (Map)  `,
  },
  {
    id: 2,
    title: "Mutton curry",
    category: "lunch",
    price: "190₹",
    restaurant: "restaurant: lucky kabab",
    img: "./images/Mutton Curry lucky kabab.jpg",
    desc: `Address:4-165 SY-139/B, Gandi Maisamma, hyderabad - 500043, Near Gandi Maisamma X Road (Map)  `,
  },
  {
    id: 3,
    title: "kaju biryani",
    category: "lunch",
    price: "220₹",
    restaurant: "restaurant:shubam",
    img: "./images/kaju biryani shubam.jpg",
    desc: `Address: Shapur Nagar Main Rd, Phase 1, IDA Jeedimetla, Chinthal, Jeedimetla, Hyderabad, Telangana 500055.`,
  },
  {
    id: 4,
    title: "paneer mandi",
    category: "dinner",
    price: "190₹",
    restaurant: "restaurant:Friends mandi",
    img: "./images/paneer mandi friends.jpg",
    desc: `Address:NO.165, D POCHAMPALLY, SURVEY NO. 165, GANDIMAISAMMA , Circle No.15 (Quthbullapur),`,
  },
  {
    id: 5,
    title: "paneer tikka",
    category: "lunch",
    price: "300₹",
    restaurant: "restaurant:shubam",
    img: "./images/paneer tikka shubam.jpg",
    desc: `Address: Shapur Nagar Main Rd, Phase 1, IDA Jeedimetla, Chinthal, Jeedimetla, Hyderabad, Telangana 500055 `,
  },
  {
    id: 6,
    title: "veg spring roll",
    category: "snacks",
    price: "300₹",
    restaurant: "restaurant:shubam",
    img: "./images/veg spring roll snacks.jpg",
    desc: `Address: Shapur Nagar Main Rd, Phase 1, IDA Jeedimetla, Chinthal, Jeedimetla, Hyderabad, Telangana 500055`,
  },
  {
    id: 7,
    title: "chicken mandi",
    category: "lunch",
    price: "190₹",
    restaurant: "restaurant:friends mandi",
    img: "./images/chicken mandi friends.jpg",
    desc: `Address:NO.165, D POCHAMPALLY, SURVEY NO. 165, GANDIMAISAMMA , Circle No.15 (Quthbullapur), `,
  },
  {
    id: 8,
    title: "Butter naan",
    category: "lunch",
    price: "50₹",
    restaurant: "restaurant:shubam",
    img: "./images/Butter naan shubam.jpg",
    desc: `Address: Shapur Nagar Main Rd, Phase 1, IDA Jeedimetla, Chinthal, Jeedimetla, Hyderabad, Telangana 500055 `,
  },
  {
    id: 9,
    title: "Drinks",
    category: "Drinks",
    price: "starts from 15₹",
    restaurant: "restaurant:cafe club",
    img: "./images/drinks cafe club.jpg",
    desc: `Address:Gandimaisamma, Suraram Road left to the main road`,
  },
  {
    id: 10,
    title: "sweet",
    category: "snacks",
    price: "120₹",
    restaurant: "restaurant:Sri Gokul sweets and bakers",
    img: "./images/sweet  sri gokul shapur.webp",
    desc: `Adrress:GC7W+8VV, Vegetable Market Rd, Prasanth Nagar, Shapur Nagar, Chinthal, Jeedimetla, Hyderabad, Telangana 500055`,
  },
  {
    id: 11,
    title: "sweets and mixtures",
    category: "snacks",
    price: "starts from 50₹",
    restaurant: "restaurant:Sri Gokul sweets and bakers",
    img: "./images/sweets and mixtures gokul sweets shapur.jpg",
    desc: `Adrress:GC7W+8VV, Vegetable Market Rd, Prasanth Nagar, Shapur Nagar, Chinthal, Jeedimetla, Hyderabad, Telangana 500055`,
  },
  {
    id: 12,
    title: "Butter naan",
    category: "lunch",
    price: "50₹",
    restaurant: "restaurant:Shubam",
    img: "./images/Butter naan shubam.jpg",
    desc: `Address: Shapur Nagar Main Rd, Phase 1, IDA Jeedimetla, Chinthal, Jeedimetla, Hyderabad, Telangana 500055`,
  },
  {
    id: 13,
    title: "chicken biryani",
    category: "dinner",
    restaurant: "restaurant:Lucky kabab",
    price: "single:120₹ Full:210₹",
    img: "./images/chicken biryani lucky kabab.jpg",
    desc: `Address:4-165 SY-139/B, Gandi Maisamma, hyderabad - 500043, Near Gandi Maisamma X Road (Map) `,
  },
  {
    id: 14,
    title: "breakfast ",
    category: "breakfast",
    restaurant: "restaurant:New Sagar",
    price: "starts from 30₹",
    img: "./images/MOMO cafe breakfast.png",
    desc: `Address: x' road, beside land registation office, Venkatarama Colony, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 17,
    title: "cheese Dosa",
    category: "breakfast",
    restaurant: "restaurant:Sri Raghavendra",
    price: "30₹",
    img: "./images/Cheese Dosa Sri Raghavendra.PNG",
    desc: `Address:Sri Raghavendra Bhavan, Hyderabad, Gandi Maisamma, Rangareddy - 500043`,
  },
  {
    id: 19,
    title: "chicken handi",
    category: "dinner",
    restaurant: "restaurant:Shubam",
    price: "400₹",
    img: "./images/chicken handi shubam.webp",
    desc: `Address: Shapur Nagar Main Rd, Phase 1, IDA Jeedimetla, Chinthal, Jeedimetla, Hyderabad, Telangana 500055`,
  },
  {
    id: 20,
    title: "Dil pasand",
    category: "snacks",
    restaurant: "restaurant:New Sagar",
    price: "80₹",
    img: "./images/Dil pasand New sagar.PNG",
    desc: `Address: x' road, beside land registation office, Venkatarama Colony, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 21,
    title: "finBiscuit",
    category: "snacks",
    restaurant: "restaurant:New Sagar",
    price: "10₹",
    img: "./images/finBiscuit New sagar Restarant.PNG",
    desc: `Address: x' road, beside land registation office, Venkatarama Colony, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 22,
    title: "kababs",
    category: "snacks",
    restaurant: "restaurant:Grill house",
    price: "Half:130₹ Full:230",
    img: "./images/kababs Grill house shapur.PNG",
    desc: `Address:House 9-3, Sanjay Gandhi Nagar, Near Shapur Nagar, Qutubullapur, Circle 25, Jeedimetla, Hyderabad`,
  },
  {
    id: 23,
    title: "kaju Biryani",
    category: "snacks",
    restaurant: "restaurant:Grill house",
    price: "190₹",
    img: "./images/kaju biryani grill house.PNG",
    desc: `Address:House 9-3, Sanjay Gandhi Nagar, Near Shapur Nagar, Qutubullapur, Circle 25, Jeedimetla, Hyderabad`,
  },
  {
    id: 25,
    title: "Mysore bajji",
    category: "snacks",
    restaurant: "restaurant:Sai Darshini",
    price: "30₹",
    img: "./images/mysore bajji sai darshini.PNG",
    desc: `Address: Plot No.101, Ushodaya Towers, Shapur Nagar Main Rd, IDA Jeedimetla, Chinthal, Jeedimetla, Hyderabad, Telangana 500055`,
  },
  {
    id: 26,
    title: "Chicken Noodles",
    category: "snacks",
    restaurant: "restaurant:V Eat N Joy",
    price: "80₹",
    img: "./images/Noodles V Eat N Joy snacks.PNG",
    desc: `Address:Plot 55, 56, Phase 2, Block B, Qutubullapur, Jeedimetla, Hyderabad`,
  },
  {
    id: 27,
    title: "Oreo shake",
    category: "Drinks",
    restaurant: "restaurant:New Sagar",
    price: "100₹",
    img: "./images/Oreo shake New sagar.PNG",
    desc: `Address: x' road, beside land registation office, Venkatarama Colony, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 28,
    title: "Parata",
    category: "snacks",
    restaurant: "restaurant:Sai darshini",
    price: "45₹",
    img: "./images/paratha sai darshini.PNG",
    desc: `Address: Plot No.101, Ushodaya Towers, Shapur Nagar Main Rd, IDA Jeedimetla, Chinthal, Jeedimetla, Hyderabad, Telangana 500055`,
  },
  {
    id: 29,
    title: "puri",
    category: "breakfast",
    restaurant: "restaurant:Sri Raghavendra",
    price: "30₹",
    img: "./images/puri Sri Raghavendra gandi.PNG",
    desc: `Address:Sri Raghavendra Bhavan, Hyderabad, Gandi Maisamma, Rangareddy - 500043`,
  },
  {
    id: 30,
    title: "Tie Biscuit",
    category: "breakfast",
    restaurant: "restaurant:New Sagar",
    price: "15₹",
    img: "./images/Tie biscuit New sagar.PNG",
    desc: `Address: x' road, beside land registation office, Venkatarama Colony, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 31,
    title: "Veg Burger",
    category: "breakfast",
    restaurant: "restaurant:New Sagar",
    price: "40₹",
    img: "./images/Veg Burger New sagar .PNG",
    desc: `Address: x' road, beside land registation office, Venkatarama Colony, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 32,
    title: "Veg manchuria",
    category: "snacks",
    restaurant: "restaurant:Royal Sagar",
    price: "90₹",
    img: "./images/veg manchuria snacks Royal sagar .PNG",
    desc: `Address:near bus stop, Phase 1, Shapur Nagar, Chinthal, Jeedimetla, Hyderabad, Telangana 500055`,
  },
  {
    id: 33,
    title: "Veg manchuria",
    category: "snacks",
    restaurant: "restaurant:V Eat N Joy",
    price: "80₹",
    img: "./images/Veg manchuria V Eat N Joy snacks.PNG",
    desc: `Address:Plot 55, 56, Phase 2, Block B, Qutubullapur, Jeedimetla, Hyderabad`,
  },
  {
    id: 34,
    title: "wada",
    category: "breakfast",
    restaurant: "restaurant:Sai darshini",
    price: "30₹",
    img: "./images/wada sai darshini.PNG",
    desc: `Address: Plot No.101, Ushodaya Towers, Shapur Nagar Main Rd, IDA Jeedimetla, Chinthal, Jeedimetla, Hyderabad, Telangana 500055`,
  },
  {
    id: 35,
    title: "lemonade",
    category: "breakfast",
    restaurant: "restaurant:Classic",
    price: "50₹",
    img: "./images/classic lemonade.PNG",
    desc: `Address:Bahadurpally X Road, Jeedimetla, Hyderabad - 500055, Beside Humsafar Dhaba`,
  },
  {
    id: 36,
    title: "oreo shake",
    category: "breakfast",
    restaurant: "restaurant:Tea house",
    price: "100₹",
    img: "./images/orea tea house.PNG",
    desc: `Address: Sundar Rao Nagar, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 37,
    title: "pista shake",
    category: "Drinks",
    restaurant: "restaurant:Tea home",
    price: "120₹",
    img: "./images/pistashake tea home.PNG",
    desc: `Address: Plot No. 1000 , Suraram Colony Bus Stop , Jeedimetla, Suraram Colony, Dayanand Nagar, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 38,
    title: "rose shake",
    category: "Drinks",
    restaurant: "restaurant:Tea home",
    price: "110₹",
    img: "./images/rose shake tea home.PNG",
    desc: `Address: Plot No. 1000 , Suraram Colony Bus Stop , Jeedimetla, Suraram Colony, Dayanand Nagar, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 39,
    title: "venella ",
    category: "Drinks",
    restaurant: "restaurant:Tea home",
    price: "100₹",
    img: "./images/venella ice cream tea home.PNG",
    desc: `Address: Plot No. 1000 , Suraram Colony Bus Stop , Jeedimetla, Suraram Colony, Dayanand Nagar, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 40,
    title: "Badam tea",
    category: "Drinks",
    restaurant: "restaurant:Tea home",
    price: "25₹",
    img: "./images/Badam tea tea home.PNG",
    desc: `Address: Plot No. 1000 , Suraram Colony Bus Stop , Jeedimetla, Suraram Colony, Dayanand Nagar, Suraram, Hyderabad, Telangana 500055`,
  },
  {
    id: 41,
    title: "lime ment cooler",
    category: "Drinks",
    restaurant: "restaurant:Tea home",
    price: "80₹",
    img: "./images/lime ment cooler tea home.PNG",
    desc: `Address: Plot No. 1000 , Suraram Colony Bus Stop , Jeedimetla, Suraram Colony, Dayanand Nagar, Suraram, Hyderabad, Telangana 500055`,
  },
];
export default menu;
